name: build builder

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref_name == 'master' && 'latest' || github.ref_name }}
  
jobs:
  builder-build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Build with docker
      run: docker build --tag ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }} .
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish image
      run: docker push ${{ env.REGISTRY }}/${{ github.repository }}:${{ env.IMAGE_TAG }}

# vim: set ts=2 et sw=2: ai 

