name: build audioserve

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git reference to checkout and build'
        required: true
        default: 'master'
        type: string
  
env:
  REGISTRY: ghcr.io
  BUILDER_IMAGE: srd424/audioserve-builder
  BUILD_TYPE: release
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout audioserve source
      uses: actions/checkout@v3
      with:
        repository: 'izderadicka/audioserve'
        path: audioserve-src
        ref: ${{ inputs.ref }}
    - name: generate release name
      id: genrel
      run: |
        if [ "${{ inputs.ref }}" = "master" ]; then
          rev=$(cd audioserve-src && git rev-parse --short HEAD)
          echo "::set-output name=release_ref::trunk-$rev"
          echo "::set-output name=release_tag::trunk-$rev_$(date +%y%m%d%H%M)"
        else
          echo "::set-output name=release_ref::${{ inputs.ref }}"
          echo "::set-output name=release_tag::${{ inputs.ref }}_$(date +%y%m%d%H%M)"
        fi
    - name: cache build cache
      uses: actions/cache@v3
      with:
        path: build
        key: as0-${{ env.BUILD_TYPE }}-${{ steps.genrel.outputs.release_ref }}
        restore-keys: |
          as0-${{ env.BUILD_TYPE }}-
          as0-
          as
    - name: Docker pull
      run: docker pull ${{ env.REGISTRY }}/${{ env.BUILDER_IMAGE }}
    - name: Docker run
      run: mkdir -p ./result ./build && docker run -v ${GITHUB_WORKSPACE}/audioserve-src:/src -v $PWD/build:/build -v $PWD/result:/result -e CARGO_PROFILE=${{ env.BUILD_TYPE }} ${{ env.REGISTRY }}/${{ env.BUILDER_IMAGE }}
    - name: zip results
      run: zip -r audioserve_aarch64.zip result
    - name: Release zip
      uses: softprops/action-gh-release@v1
      with:
        files: audioserve_aarch64.zip
        tag_name: ${{ steps.genrel.outputs.release_tag }}
