name: build audioserve

on:
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  BUILDER_IMAGE: srd424/audioserve-builder
  
jobs:
  builder-build:
    runs-on: ubuntu-20.04
    steps:
    - name: cache build cache
      uses: actions/cache@v3
      with:
        path: build
        key: audioserve
    - name: Docker pull
      run: docker pull ${{ env.REGISTRY }}/${{ env.BUILDER_IMAGE }}
    - name: Docker run
      run: mkdir -p ./result ./build && docker run -v $PWD/build:/build -v $PWD/result:/result ${{ env.REGISTRY }}/${{ env.BUILDER_IMAGE }}
#    - name: save results
#      uses: actions/upload-artifact@v3
#      with:
#        name: audioserve
#        path: result
    - name: zip results
      run: zip -r audioserve_aarch64.zip result
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Release zip
      uses: softprops/action-gh-release@v1
      with:
        files: audioserve_aarch64.zip
        tag_name: ${{ steps.tag.outputs.release_tag }}
